services:
    Helix Claude:
        container_name: Helix Claude
        restart: always
        working_dir: /var/www/html
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - Helix Claude
        depends_on:
            - postgres
            - redis
            - soketi
    postgres:
        image: postgres:15-alpine
        container_name: Helix Claude-db
        restart: always
        networks:
            - Helix Claude
    redis:
        image: redis:7-alpine
        container_name: Helix Claude-redis
        restart: always
        networks:
            - Helix Claude
    soketi:
        container_name: Helix Claude-realtime
        extra_hosts:
            - host.docker.internal:host-gateway
        restart: always
        networks:
            - Helix Claude
networks:
    Helix Claude:
        name: Helix Claude
        driver: bridge
        external: false
